image:
  repository: ghcr.io/benzac708/zachara-dev
  digest: sha256:b432bff6007efddaf10b157565c1f8b074280833225f33533b54d476e536f515
  pullPolicy: Always

ingress:
  hosts:
    - host: zachara.dev
      paths:
        - path: /
          pathType: Prefix
    - host: www.zachara.dev
      paths:
        - path: /
          pathType: Prefix
