image:
  repository: ghcr.io/benzac708/zachara-dev
  digest: sha256:902f1a0495287c474131a5de71dd5e4505069f7acdec8eb87793a91fbd8e2dc4
  pullPolicy: IfNotPresent

ingress:
  hosts:
    - host: zachara.dev
      paths:
        - path: /
          pathType: Prefix
    - host: www.zachara.dev
      paths:
        - path: /
          pathType: Prefix
