image:
  repository: ghcr.io/benzac708/zachara-dev
  digest: sha256:7319be8af218a362884068f650c618687b2f9af34983144728eb0ae39d8d87eb
  pullPolicy: Always

ingress:
  hosts:
    - host: zachara.dev
      paths:
        - path: /
          pathType: Prefix
    - host: www.zachara.dev
      paths:
        - path: /
          pathType: Prefix
